field: 8fd439fe-660f-4cac-8ddf-b71b8ad6276f # Tour POIs
fieldLayouts:
  1b720c1b-b66f-4f5c-bd7d-a64b1bd32367:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a676166-cd4f-4c4e-a7ee-afca5c68fc2d # Astro Object
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3272191-3ca1-43fb-b7f7-5ff431f1d9f0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d6f8219d-2a83-4ee6-967e-10720dec037b # FOV
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 357e9018-33df-4199-b8b3-77c81b9bad20
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fe1835fb-8bd0-4e5a-b637-0e94330568ac # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 326815f2-00b3-460f-bd49-bbc6159f015e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6e1a5aaf-7bc6-457d-b979-4f3b9d4ce4c0 # Audio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9621155e-de08-4228-9aa2-5a65b75fd725
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9acbaaa2-a8e8-4f68-a495-98b3e2d8ed13 # Zoom Out Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e733cf0d-5f59-4f8d-87f1-efdeae771fc5
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f179ae9d-f7cc-4d51-824b-393c7ab4879d # Zoom Out FOV
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f954046-ce9a-48b6-b70b-aca6792a5ba1
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a946a572-4818-4836-be34-95b4395d603a # Pan Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2b50372-4952-4e30-a67e-5104674c497e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 51928716-cd54-492b-8292-3e1dea11aa9f # Zoom In Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1467247f-0793-4572-baa1-df58e083fc0c
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 9e973a7f-2421-499d-ad1b-39e7b44f5384
        userCondition: null
fields:
  4a676166-cd4f-4c4e-a7ee-afca5c68fc2d: # Astro Object
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: astroObject
    instructions: null
    name: 'Astro Object'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: false
      sources:
        - 'section:e2eb2e80-8e02-4a68-aa81-3d488f80543d' # Astro Object
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  6e1a5aaf-7bc6-457d-b979-4f3b9d4ce4c0: # Audio
    columnSuffix: dblnzfer
    contentColumnType:
      - 'cantoId:string'
      - 'cantoAlbumId:string'
      - 'cantoAssetData:json'
      - 'cantoAlbumData:json'
    fieldGroup: null
    handle: audio
    instructions: 'Audio that will play during this tour stop'
    name: Audio
    searchable: false
    settings:
      cantoAssetPickerType: singleImagePicker
    translationKeyFormat: null
    translationMethod: site
    type: lsst\cantodamassets\fields\CantoDamAsset
  9acbaaa2-a8e8-4f68-a495-98b3e2d8ed13: # Zoom Out Time
    columnSuffix: szjpwegf
    contentColumnType: 'decimal(11,1)'
    fieldGroup: null
    handle: zoomOutTime
    instructions: 'Time to zoom out after this POI'
    name: 'Zoom Out Time'
    searchable: false
    settings:
      decimals: 1
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: seconds
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  51928716-cd54-492b-8292-3e1dea11aa9f: # Zoom In Time
    columnSuffix: xjnnebcz
    contentColumnType: 'decimal(11,1)'
    fieldGroup: null
    handle: zoomInTime
    instructions: 'Time to zoom in to the next POI after this POI'
    name: 'Zoom In Time'
    searchable: false
    settings:
      decimals: 1
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: seconds
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  a946a572-4818-4836-be34-95b4395d603a: # Pan Time
    columnSuffix: kuiphvxs
    contentColumnType: 'decimal(11,1)'
    fieldGroup: null
    handle: panTime
    instructions: 'Time to pan to the next POI after this POI'
    name: 'Pan Time'
    searchable: false
    settings:
      decimals: 1
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: seconds
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  d6f8219d-2a83-4ee6-967e-10720dec037b: # FOV
    columnSuffix: null
    contentColumnType: 'decimal(16,6)'
    fieldGroup: null
    handle: fov
    instructions: null
    name: FOV
    searchable: false
    settings:
      decimals: 6
      defaultValue: 20
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: degrees
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  f179ae9d-f7cc-4d51-824b-393c7ab4879d: # Zoom Out FOV
    columnSuffix: zhzwhfbf
    contentColumnType: 'decimal(16,6)'
    fieldGroup: null
    handle: zoomOutFov
    instructions: 'FOV to zoom out to after this POI'
    name: 'Zoom Out FOV'
    searchable: false
    settings:
      decimals: 6
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: degrees
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  fe1835fb-8bd0-4e5a-b637-0e94330568ac: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: tourPoi
name: 'Tour POI'
sortOrder: 1
