runtime: custom
env: flex

runtime_config:
    document_root: craftcms/web/

vm_health_check:
 enable_health_check: False

manual_scaling:
  instances: 1

resources:
  memory_gb: 4

beta_settings:
  cloud_sql_instances: skyviewer:us-west1:skyviewer=tcp:5432

env_variables:
    DB_DSN: pgsql:host=<GCP Cloud SQL IP>;dbname=skyviewer
    DB_SERVER: <GCP Cloud SQL IP>
    DB_NAME: skyviewer
    DB_USER: skyviewer
    DB_PASSWORD: <Cloud SQL Password>
    DB_DATABASE: skyviewer
    DB_SCHEMA: public
    DB_DRIVER: pgsql
    DB_PORT: 5432
    DOCUMENT_ROOT: /app/craftcms/web
    SECURITY_KEY: ht6LmWF_oEqN14f7-_aVsJZ5sXIsyvmy
    APP_ID: CraftCMS--fb512aa9-7e66-42fd-b311-27165912e30e
    ENVIRONMENT: dev
    PRIMARY_SITE_URL: https://skyviewer.uw.r.appspot.com
