# docker-compose.yml
version: '2.2'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 9900:81
    depends_on:
      - skyviewer_api
    volumes_from:
      - skyviewer_api
    volumes:
      - ./config-env/default.conf:/etc/nginx/conf.d/default.conf # nginx configuration (see below)

  skyviewer_api:
    image: epo/skyviewer_api:latest
    depends_on:
      - postgres
    volumes:
      - ./:/var/www/html/
    environment:
      
      DB_DSN: pgsql:host=postgres;dbname=skyviewer
      DB_SERVER: postgres
      DB_NAME: skyviewer
      DB_USER: skyviewer
      DB_PASSWORD: zkyvi3w3r
      DB_DATABASE: skyviewer
      DB_SCHEMA: public
      DB_DRIVER: pgsql
      DB_PORT: 5432

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_USER: skyviewer
      POSTGRES_PASSWORD: zkyvi3w3r
      POSTGRES_DB: skyviewer
    volumes:
      # Persistent data
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  driver: 