# docker-compose.yml
version: '2.2'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 9900:81
    depends_on:
      - craft
    volumes_from:
      - craft
    volumes:
      - ./config-env/default.conf:/etc/nginx/conf.d/default.conf # nginx configuration (see below)

  craft:
    image: epo/craft_cms_starter:latest
    depends_on:
      - postgres
    volumes:
      - ./:/var/www/html/
    environment:
      
      DB_DSN: pgsql:host=postgres;dbname=craft
      DB_SERVER: postgres
      DB_NAME: craft
      DB_USER: craft
      DB_PASSWORD: rootroot
      DB_DATABASE: craft
      DB_SCHEMA: public
      DB_DRIVER: pgsql
      DB_PORT: 5432

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_USER: craft
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: craft
    volumes:
      # Persistent data
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  driver: 