services:
  redis:
    image: redis
    ports:
      - 6378:6378
  postgres:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: skyviewer
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: zkyvi3w3r
    volumes:
      - ./db/skyviewer.sql:/skyviewer.sql
    healthcheck:
      test: [ "CMD-SHELL", "export PGPASSWORD=$${POSTGRES_PASSWORD}; pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  craft:
    build: ./
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./api:/var/www/html
      - .env:/var/secrets/.env
    environment:
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      PORT: 8080
      APP_ID: CraftCMS--d337aaa2-c2ae-4cfb-9b3d-fe0c268ff065
      CP_TRIGGER: admin
      DB_DRIVER: pgsql
      DB_SERVER: postgres
      DB_PORT: 5432
      DB_DATABASE: skyviewer
      DB_USER: skyviewer
      DB_PASSWORD: zkyvi3w3r
      DB_SCHEMA: public
      ENABLE_MEMCACHED: true
      ENVIRONMENT: dev
      GCP_PROJECT_ID: skyviewer
      GCS_ASSET_BUCKET: https://storage.googleapis.com/craft-test-erosas
      MEMCACHED_IP: cache
      MEMCACHED_PORT: 11211
      PRIMARY_SITE_URL: http://localhost:8080
      SECURITY_KEY: abcdef0123456789
      ROSAS_APP_ID: 52ff8ed9d6874d48a3bef9621bc1af26
      ROSAS_SECRET_KEY: 1d12371b7dee4a7d87c6886d777056095642d672cacf4138b848b7b01173f019
      ROSAS_AUTH_ENDPOINT: https://oauth.canto.com/oauth/api/oauth2/token?app_id={appId}&app_secret={secretKey}&grant_type=client_credentials&refresh_token=
      ROSAS_RETRIEVE_ASSET_ENDPOINT: https://rubin.canto.com/api/v1/image/
    restart: always