dateModified: 1626287443
email:
  fromEmail: erosas@lsst.org
  fromName: 'Skyviewer API'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: 'Skyviewer API'
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
