color: null
description: null
fieldLayouts:
  eece55ab-46e4-40e3-b1e5-824bea127ca9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-30T21:32:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 34dea395-8beb-4307-83db-35f8188d316b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-30T21:32:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4286f2c2-ef6e-4606-8160-8a241488a1f6 # Guided Experiences
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40fd3296-2a36-4e87-beba-4a82d3c6aec4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2300370f-8b12-48f2-af60-0a70848ee2e4
        userCondition: null
handle: guidedExperiences
hasTitleField: true
icon: null
name: 'Guided Experiences'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
