color: null
description: null
fieldLayouts:
  0fc0ae09-e999-401a-94f3-c849d44a6fc0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 6f7c799f-429a-486c-bde4-a5bd5ece3a78
            handle: body
            includeInCards: true
            instructions: null
            label: Body
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b9b4128-13e1-4965-8393-5c620084926d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7bb4f45d-4e54-4f6d-93d4-ce318c2af596
        userCondition: null
handle: introBlock
hasTitleField: false
icon: null
name: 'Intro Content Block'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
