fieldLayouts:
  68a3f1d2-8b35-4dc1-885e-7254b1471879:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0e613588-0d29-44de-90f3-a64ab5e52181
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a653768-6c25-44d4-815e-182cd324b043 # Ra
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f55bdc8c-a4f7-48a6-a7c2-54aba385f872
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c8a76131-a217-46f6-9b2a-88d4f2a2f7de # Dec
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d0e8be1-b28a-4e9d-95d6-b39be628870d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a0521bda-0df4-4937-9d6e-1534dfb98b58 # Field of View (FOV) Initial
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d61fa58c-5337-4b6d-94c5-599923304cf0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: 39e98af8-19d3-488a-b284-b3d9aced72a3
            userCondition: null
          -
            elementCondition: null
            fieldUid: 0732995e-10da-4be7-944b-51b1135d12eb # Field of View (FOV) Minimum
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc792c76-deec-48ea-9bdf-675c46fc21e9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 455216e8-f949-4521-911f-d50895102cd4 # Field of View (FOV) Maximum
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cf9d7cd-6eba-4fe6-8f55-17fbb0d7f1f7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 179c3988-2d82-48de-bc01-3687d42a7578
            userCondition: null
          -
            elementCondition: null
            fieldUid: 69d17c85-9486-42c7-815a-45cd69c9129b # Surveys
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ff13023-edea-4534-bbba-efa5b4a164a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b2ec96c-45a8-4d87-ae02-5c49c4f1ebdc
        userCondition: null
handle: skysynth
hasTitleField: false
name: SkySynth
section: d53d9e9e-bc1b-43dc-87eb-d0e6d1323238 # SkySynth
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
