fieldLayouts:
  a590a1dc-4372-4d00-9cf8-267c5e5e93f1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4adca7fa-cb0b-4cf9-96b5-5fa10be7f599
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fe3ef1fd-33fa-4aeb-9ed2-9e74f6694377 # Path
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f781f5fb-82b9-40f1-9233-0f2dc3e6c89c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3f50442-f90e-42e6-986e-b2426abedaca # Target
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51ef593c-78ef-47eb-91c8-3cbc9903372f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0732995e-10da-4be7-944b-51b1135d12eb # Field of View (FOV) Minimum
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf66f2ea-3517-42d4-b599-24719ca37373
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 455216e8-f949-4521-911f-d50895102cd4 # Field of View (FOV) Maximum
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3722993c-b3ad-4043-bf70-b7168bf6f03a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a0521bda-0df4-4937-9d6e-1534dfb98b58 # Field of View (FOV) Initial
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37352fca-4358-45c1-8cd9-548a151483dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'HiPS Properties'
            type: craft\fieldlayoutelements\Heading
            uid: 048996e0-308c-497b-bee7-1efcfde93ef2
            userCondition: null
          -
            elementCondition: null
            fieldUid: d43d64da-ee7e-4be7-bdf7-7a4af1994dad # Image Format
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36b01bc0-2c4a-43e8-b7f1-ac7025748ea7
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 3ea0147c-d31c-48ca-b25c-e361191e8b8b # Max Order
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed2ea434-c9ba-4924-a356-793a70cf4573
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 47737e5d-6fd7-42dd-95c3-e2c69caa42d5 # Tile Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b5ed8cc-9885-40b5-967d-cffa348a14e9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 69a9149f-522c-4bae-9964-ce7bc440f181 # Coordinate Frame
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e38b1f64-0026-4b1c-a4b0-b3665727faa7
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 3d8bf9a8-2d81-487b-b46a-6f791f933930
        userCondition: null
handle: surveys
hasTitleField: true
name: Survey
section: 02e3155f-23cf-4f36-a734-a3f447d04e85 # Survey
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
