fieldLayouts:
  3aff80ee-9ac7-4a11-8a1b-ed7f358711b6:
    tabs:
      -
        elements:
          -
            fieldUid: 45720ab9-15e3-4cdc-8103-9c0495d2c1d2 # Site Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d2cd37c9-0e8a-4bbb-aff0-13584d58279b # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Metadata
        sortOrder: 1
handle: siteInfo
name: 'Site Info'
