contentColumnType: text
fieldGroup: a3b0cf34-24af-41fe-8047-b1e5b65d5bd0 # Catalog
handle: description
instructions: 'What does this HiPS catalog contain?'
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
