contentColumnType: text
fieldGroup: 8d6803f5-ca34-46d8-a8d5-869896e34b65 # Tour
handle: introHeading
instructions: ''
name: 'Intro Heading'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
