contentColumnType: string(255)
fieldGroup: a3b0cf34-24af-41fe-8047-b1e5b65d5bd0 # Catalog
handle: path
instructions: ''
name: Path
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
