contentColumnType: string
fieldGroup: 8d6803f5-ca34-46d8-a8d5-869896e34b65 # Tour
handle: pois
instructions: ''
name: 'Points of Interest'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:4a76eb6e-e209-42df-8ef6-43f1e5f7f745' # Points of Interest
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
