contentColumnType: string
fieldGroup: 8d6803f5-ca34-46d8-a8d5-869896e34b65 # Tour
handle: tourVariety
instructions: ''
name: Variety
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Tour
        -
          - value
          - tour
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Hall-of-Fame
        -
          - value
          - hallOfFame
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
