fieldLayouts:
  1bd45809-7be7-4083-bdbc-bceb5876fdc8:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 36cb7208-d072-48ac-af5e-c034035afdfd # Variety Handle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7f01b564-7d49-4139-be9d-07d369fd3408 # Thumbnail Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: tourVariety
name: 'Tour Variety'
siteSettings:
  763c0189-f6eb-419c-9ca2-2574a743768a: # EN
    hasUrls: true
    template: null
    uriFormat: 'tour-variety/{slug}'
  a6b28fea-2f0c-49a2-b82c-fd16c51d9511: # ES
    hasUrls: true
    template: null
    uriFormat: 'tour-variety/{slug}'
structure:
  maxLevels: 1
  uid: 8df90f53-f24a-42e0-81aa-44869bab2bd1
