field: 8fd439fe-660f-4cac-8ddf-b71b8ad6276f # Tour POIs
fieldLayouts:
  1b720c1b-b66f-4f5c-bd7d-a64b1bd32367:
    tabs:
      -
        elements:
          -
            fieldUid: fe1835fb-8bd0-4e5a-b637-0e94330568ac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9d28ee9c-bac6-404e-a24f-afde8a75ad1b # Point of Interest
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1f5ddbcd-4f3f-495c-95d9-dcd6af9e3f6f # Astro Object
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1f5ddbcd-4f3f-495c-95d9-dcd6af9e3f6f: # Astro Object
    contentColumnType: string
    fieldGroup: null
    handle: astroObject
    instructions: ''
    name: 'Astro Object'
    searchable: true
    settings:
      allowSelfRelations: true
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources:
        - 'section:e2eb2e80-8e02-4a68-aa81-3d488f80543d' # Astro Object
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  9d28ee9c-bac6-404e-a24f-afde8a75ad1b: # Point of Interest
    contentColumnType: string
    fieldGroup: null
    handle: poi
    instructions: ''
    name: 'Point of Interest'
    searchable: true
    settings:
      allowSelfRelations: true
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources:
        - 'section:4a76eb6e-e209-42df-8ef6-43f1e5f7f745' # Points of Interest
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  fe1835fb-8bd0-4e5a-b637-0e94330568ac: # Description
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: tourPoi
name: 'Tour POI'
sortOrder: 1
