field: 8fd439fe-660f-4cac-8ddf-b71b8ad6276f # Tour POIs
fieldLayouts:
  1b720c1b-b66f-4f5c-bd7d-a64b1bd32367:
    tabs:
      -
        elements:
          -
            fieldUid: fe1835fb-8bd0-4e5a-b637-0e94330568ac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d6f8219d-2a83-4ee6-967e-10720dec037b # FOV
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4a676166-cd4f-4c4e-a7ee-afca5c68fc2d # astroObject
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1f5ddbcd-4f3f-495c-95d9-dcd6af9e3f6f # Astro Object
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4a676166-cd4f-4c4e-a7ee-afca5c68fc2d: # astroObject
    contentColumnType: string
    fieldGroup: null
    handle: astroObject
    instructions: ''
    name: astroObject
    searchable: false
    settings:
      allowSelfRelations: true
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources:
        - 'section:e2eb2e80-8e02-4a68-aa81-3d488f80543d' # Astro Object
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  d6f8219d-2a83-4ee6-967e-10720dec037b: # FOV
    contentColumnType: integer(10)
    fieldGroup: null
    handle: fov
    instructions: ''
    name: FOV
    searchable: false
    settings:
      decimals: 0
      defaultValue: '20'
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  fe1835fb-8bd0-4e5a-b637-0e94330568ac: # Description
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: tourPoi
name: 'Tour POI'
sortOrder: 1
