fieldLayouts:
  ab7474e7-fb73-455c-a412-040560a3da56:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: cantoDam
hasUrls: true
name: 'Canto DAM'
settings:
  dummySetting: ''
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: rosas\dam\volumes\DAMVolume
url: $CANTO_ASSET_BASEURL
