fieldLayouts:
  3bbfc7cd-6a6b-4534-bd52-9b7566850e2a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: 5ef8f422-6773-4891-99b9-f56cdb8bced4 # Alternate Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: tourImages
hasUrls: true
name: 'Tour Images'
settings:
  bucket: $GCS_ASSET_BUCKET
  bucketSelectionMode: manual
  expires: '5 minutes'
  keyFileContents: ''
  projectId: $GCP_PROJECT_ID
  subfolder: tours
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\googlecloud\Volume
url: '@gcsBucketUrl'
