columnSuffix: null
contentColumnType: string
handle: astroObjects
instructions: null
name: 'Astro Objects'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:e2eb2e80-8e02-4a68-aa81-3d488f80543d' # Astro Object
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
