columnSuffix: null
contentColumnType: string
handle: astroImage
instructions: null
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:860a3a7b-7ed5-4997-9a40-0d00e58b77d0' # Astro Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:85d34514-ec13-4850-a272-a3ab1bc790ef'
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:860a3a7b-7ed5-4997-9a40-0d00e58b77d0' # Astro Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
