columnSuffix: null
contentColumnType: string
handle: catalogVariety
instructions: null
name: Variety
searchable: true
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Stars
        -
          - value
          - star
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Galaxies
        -
          - value
          - galaxy
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Nebulas
        -
          - value
          - nebula
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Transients
        -
          - value
          - transient
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Goals
        -
          - value
          - goal
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Landmarks
        -
          - value
          - landmark
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
