columnSuffix: null
contentColumnType: 'decimal(8,6)'
fieldGroup: 8d6803f5-ca34-46d8-a8d5-869896e34b65 # Tour
handle: dec
instructions: Declination
name: Dec
searchable: false
settings:
  decimals: 6
  defaultValue: null
  max: 90
  min: -90
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
