columnSuffix: klgmoxyx
handle: dec2
instructions: null
name: 'Tour POIs - Tour POI - Dec'
searchable: false
settings:
  decimals: 6
  defaultValue: null
  max: 90
  min: -90
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: °
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
