columnSuffix: null
contentColumnType: integer(10)
handle: duration
instructions: 'In minutes'
name: Duration
searchable: false
settings:
  decimals: 0
  defaultValue: 5
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
