columnSuffix: null
contentColumnType: text
handle: factsHeading
instructions: null
name: 'Fun Facts Heading'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Fun Facts'
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
