columnSuffix: null
contentColumnType: string
handle: factsContentBlocks
instructions: null
name: 'Fun Facts Content Blocks'
searchable: true
settings:
  entryTypes:
    -
      uid: 8944198c-ff53-4323-ad48-976efeb3f56e
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
