columnSuffix: null
contentColumnType: 'decimal(15,5)'
handle: fov
instructions: 'A number indicating the initial zoom level'
name: 'Field of View (FOV) Initial'
searchable: false
settings:
  decimals: 5
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: °
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
