columnSuffix: null
contentColumnType: 'decimal(12,2)'
fieldGroup: 0ecf9feb-ab77-470b-a2de-eb396a3a4682 # Survey
handle: fovMax
instructions: 'A number greater than 0 and also greater than the FOV min'
name: 'Field of Vision (FOV) Maximum Value'
searchable: false
settings:
  decimals: 2
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
