columnSuffix: null
contentColumnType: 'decimal(12,2)'
fieldGroup: 0ecf9feb-ab77-470b-a2de-eb396a3a4682 # Survey
handle: fovMin
instructions: 'An integer greater than 0 and less than the FOV max value.'
name: 'Field of Vision (FOV) Minimum Value'
searchable: false
settings:
  decimals: '2'
  defaultValue: null
  max: null
  min: '0'
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
