columnSuffix: null
contentColumnType: 'decimal(13,3)'
fieldGroup: 0ecf9feb-ab77-470b-a2de-eb396a3a4682 # Survey
handle: fovMin
instructions: 'A number greater than 0 and less than the FOV max value.'
name: 'Field of View (FOV) Minimum'
searchable: false
settings:
  decimals: 3
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: °
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
