columnSuffix: null
contentColumnType: string
handle: guidedExperiences
instructions: null
name: 'Guided Experiences'
searchable: false
settings:
  entryTypes:
    -
      uid: a279aa4f-a3ed-4363-9335-a042965bc310
  maxEntries: null
  minEntries: 1
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
