columnSuffix: null
handle: guidedExperiences
instructions: null
name: 'Guided Experiences'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - a279aa4f-a3ed-4363-9335-a042965bc310 # Experience
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
