columnSuffix: null
contentColumnType: string
fieldGroup: a3b0cf34-24af-41fe-8047-b1e5b65d5bd0 # Catalog
handle: icon
instructions: 'Icon for the marker on the UI'
name: Icon
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:82bbf6f6-1ae1-4f42-b9de-913e0cc027fc' # Icons
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: thumbs
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:a469a047-d19a-421e-97f8-c58f1bda27d7' # Tour Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:82bbf6f6-1ae1-4f42-b9de-913e0cc027fc' # Icons
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
