columnSuffix: xahhgebz
contentColumnType: string(4)
handle: imgFormat
instructions: "Formats accepted 'webp', 'png', 'jpeg' or 'fits'. Will raise an error if the HiPS does not contain tiles in this format"
name: 'Image Format'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - PNG
        -
          - value
          - png
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - WebP
        -
          - value
          - webp
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - JPEG
        -
          - value
          - jpeg
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - FITS
        -
          - value
          - fits
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
