columnSuffix: oueqopbd
contentColumnType: boolean
fieldGroup: 8d6803f5-ca34-46d8-a8d5-869896e34b65 # Tour
handle: includeInFeed
instructions: 'Include this tour in the main tours feed'
name: 'Include in feed'
searchable: false
settings:
  default: true
  offLabel: Excluded
  onLabel: Included
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
