columnSuffix: oueqopbd
contentColumnType: boolean
handle: includeInFeed
instructions: 'Include this tour in the main tours feed'
name: 'Include in feed'
searchable: false
settings:
  default: true
  offLabel: Excluded
  onLabel: Included
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
