columnSuffix: null
contentColumnType: text
handle: introSubheading
instructions: null
name: 'Intro Subheading'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
