columnSuffix: null
contentColumnType: string
handle: introContentBlocks
instructions: null
name: 'Intro Content Blocks'
searchable: true
settings:
  entryTypes:
    -
      uid: 48d995fe-6d24-48f6-904a-c54f64964387
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
