columnSuffix: ohupemjy
contentColumnType:
  - 'cantoId:string'
  - 'cantoAlbumId:string'
  - 'cantoAssetData:json'
  - 'cantoAlbumData:json'
handle: logo
instructions: 'Logo that will be shown on the landing page of the Skyviewer'
name: Logo
searchable: false
settings:
  cantoAssetPickerType: singleImagePicker
translationKeyFormat: null
translationMethod: none
type: lsst\cantodamassets\fields\CantoDamAsset
