columnSuffix: uwwdcchp
contentColumnType: smallint(2)
fieldGroup: 0ecf9feb-ab77-470b-a2de-eb396a3a4682 # Survey
handle: maxOrder
instructions: 'The maximum HEALPix order of the HiPS, i.e the HEALPix order of the most refined tile images of the HiPS.'
name: 'Max Order'
searchable: false
settings:
  decimals: 0
  defaultValue: 11
  max: 12
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
