columnSuffix: null
contentColumnType: string(255)
handle: path
instructions: null
name: Path
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
