columnSuffix: null
contentColumnType: string
handle: poiAstroObject
instructions: null
name: 'POI Astro Object'
searchable: true
settings:
  entryTypes:
    -
      uid: 82d2c4d7-37f1-458a-8a56-3cc1dcec6a0c
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
