columnSuffix: null
contentColumnType: string
fieldGroup: 8d6803f5-ca34-46d8-a8d5-869896e34b65 # Tour
handle: poiAstroObject
instructions: ''
name: 'POI Astro Object'
searchable: true
settings:
  contentTable: '{{%matrixcontent_poiastroobject}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
