columnSuffix: null
contentColumnType: integer(10)
fieldGroup: 8d6803f5-ca34-46d8-a8d5-869896e34b65 # Tour
handle: ra
instructions: 'Right Acension'
name: Ra
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
