columnSuffix: mrsdxggp
handle: ra3
instructions: null
name: 'Navigation POIs - Navigation POI - RA'
searchable: false
settings:
  decimals: 6
  defaultValue: null
  max: 360
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: °
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
