columnSuffix: null
contentColumnType: integer(10)
fieldGroup: a3b0cf34-24af-41fe-8047-b1e5b65d5bd0 # Catalog
handle: sourceSize
instructions: 'Size of the marker icons'
name: 'Source Size'
searchable: false
settings:
  decimals: 0
  defaultValue: '20'
  max: null
  min: '0'
  prefix: null
  previewCurrency: ''
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
