columnSuffix: null
contentColumnType: string
handle: surveys
instructions: 'Layered surveys, surveys will be displayed in the order they are shown, with the first survey on top.'
name: Surveys
searchable: false
settings:
  entryTypes:
    -
      uid: 17a7d431-1c2c-4a2a-a3f3-c872d55e4696
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
