columnSuffix: null
contentColumnType: text
fieldGroup: 0ecf9feb-ab77-470b-a2de-eb396a3a4682 # Survey
handle: target
instructions: 'The RA and DEC that the Skyviewer Explorer will focus on during page load, type RA first followed by a space and then DEC: <RA> <DEC>'
name: Target
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Ex: 267.0208333333 -24.7800000000'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
