columnSuffix: null
contentColumnType: text
fieldGroup: 0ecf9feb-ab77-470b-a2de-eb396a3a4682 # Survey
handle: target
instructions: 'The starting position of the Skyviewer, can either be RA and DEC in decimal degrees, separated by a space, or an object''s catalog name.'
name: Target
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'ex: 6.1608333 20.4875000, or NGC 2175'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
