columnSuffix: yzgynyxq
contentColumnType:
  - 'cantoId:string'
  - 'cantoAlbumId:string'
  - 'cantoAssetData:json'
  - 'cantoAlbumData:json'
handle: thumbnail
instructions: null
name: 'Thumbnail Image'
searchable: true
settings:
  cantoAssetPickerType: singleImagePicker
translationKeyFormat: null
translationMethod: none
type: lsst\cantodamassets\fields\CantoDamAsset
