columnSuffix: yzgynyxq
contentColumnType:
  - 'cantoId:string'
  - 'cantoAlbumId:string'
  - 'cantoAssetData:json'
  - 'cantoAlbumData:json'
fieldGroup: 8d6803f5-ca34-46d8-a8d5-869896e34b65 # Tour
handle: thumbnail
instructions: null
name: 'Thumbnail Image'
searchable: true
settings:
  cantoAssetPickerType: singleImagePicker
translationKeyFormat: null
translationMethod: none
type: lsst\cantodamassets\fields\CantoDamAsset
