columnSuffix: slrwdgrx
contentColumnType: string(3)
fieldGroup: 0ecf9feb-ab77-470b-a2de-eb396a3a4682 # Survey
handle: tileSize
instructions: 'The width of the HEALPix tile images. Mostly 512 pixels but can be 256, 128, 64, 32'
name: 'Tile Size'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - 512x512
        -
          - value
          - '512'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 256x256
        -
          - value
          - '256'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 128x128
        -
          - value
          - '128'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 64x64
        -
          - value
          - '64'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 32x32
        -
          - value
          - '32'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
