columnSuffix: null
contentColumnType: string
handle: tourVariety
instructions: null
name: Variety
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: 1
  localizeRelations: false
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:aa3e2ce5-e67a-4378-8a44-c660690cbcc3' # Tour Variety
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
