columnSuffix: null
contentColumnType: string
handle: tourPois
instructions: null
name: 'Tour POIs'
searchable: true
settings:
  entryTypes:
    -
      uid: a8b34826-6a25-4e0a-b5dc-7e9820257899
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
