columnSuffix: null
contentColumnType: string
handle: tourCategory
instructions: 'Group tours together by assigning them the same category.'
name: 'Tour Category'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:928bd2d5-bb58-4e0f-9c81-f805fcc1e135' # Guided Experience Type
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
