columnSuffix: null
contentColumnType: string
handle: tourTheme
instructions: null
name: 'Tour Theme'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: 1
  localizeRelations: false
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:40780a9f-1ee7-4c59-aaaf-159094330220' # Tour Theme
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
