columnSuffix: null
handle: tourCategory
instructions: null
name: 'Tour Category'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - General
        -
          - value
          - general
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Educational
        -
          - value
          - educational
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
