columnSuffix: null
contentColumnType: string
handle: tour
instructions: null
name: Tour
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:b22ca822-e7e2-4f8c-8be5-d3b0fcab1c9f' # Tours
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
