baseUrl: '@web/es'
enabled: true
handle: skyviewerEspanol
hasUrls: true
language: es-CL
name: 'Skyviewer Español'
primary: false
siteGroup: c1f0a2ee-3b87-486c-96ed-7e2d25fc952f # Skyviewer API
sortOrder: 2
