enableVersioning: true
handle: pois
name: 'Points of Interest'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  763c0189-f6eb-419c-9ca2-2574a743768a:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'tour-point-of-interest/{slug}'
  a6b28fea-2f0c-49a2-b82c-fd16c51d9511:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'tour-point-of-interest/{slug}'
structure:
  maxLevels: null
  uid: 9c20a2ce-242e-46ab-919e-7f35c842c8f6
type: structure
