enableVersioning: true
handle: surveys
name: Surveys
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  763c0189-f6eb-419c-9ca2-2574a743768a:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'explorer/{slug}'
  a6b28fea-2f0c-49a2-b82c-fd16c51d9511:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'explorer/{slug}'
structure:
  maxLevels: null
  uid: 505d6993-ce17-4b37-aa55-28a180963d52
type: structure
