enableVersioning: true
handle: tours
name: Tours
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  763c0189-f6eb-419c-9ca2-2574a743768a:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'tour/{slug}'
  a6b28fea-2f0c-49a2-b82c-fd16c51d9511:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'tour/{slug}'
structure:
  maxLevels: null
  uid: 2529bf86-1708-4969-b27e-0df6979598b4
type: structure
