fieldLayouts:
  1172933d-d14c-443e-a972-e0e3dae6d4f7:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 25d2c2a6-169a-461c-b67d-54294c7d22d7 # HiPS ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8a653768-6c25-44d4-815e-182cd324b043 # Ra
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c8a76131-a217-46f6-9b2a-88d4f2a2f7de # Dec
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cd879179-0c4d-47a3-90e9-61fdb3516cc4 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e76c2c25-ca53-4f4c-bd93-a5af52ebb72c # Characteristics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: astroObject
hasTitleField: true
name: 'Astro Object'
section: e2eb2e80-8e02-4a68-aa81-3d488f80543d # Astro Object
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site