defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a0c261e6-18f1-4a33-98f4-caf7ad970310 # SkySynth
handle: skysynth
maxAuthors: 1
name: SkySynth
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '@previewUrlFormat'
propagationMethod: all
siteSettings:
  763c0189-f6eb-419c-9ca2-2574a743768a: # EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: skysynth
  a6b28fea-2f0c-49a2-b82c-fd16c51d9511: # ES
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: skysynth
  e747e6c7-90f7-4e80-adce-3b5032b9b427: # JA
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: skysynth
type: single
