defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 52d4af2b-ae9b-4f2f-a90b-5c4b5ce23eb9 # Tour
handle: tours
maxAuthors: 1
name: Tours
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '@previewUrlFormat'
propagationMethod: all
siteSettings:
  763c0189-f6eb-419c-9ca2-2574a743768a: # EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{slug}'
  a6b28fea-2f0c-49a2-b82c-fd16c51d9511: # ES
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{slug}'
  e747e6c7-90f7-4e80-adce-3b5032b9b427: # JA
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{slug}'
type: channel
