name: Deploy to App Engine
on:
  push:
    branches:
      - EPO-5131
jobs:
  deploy_this_noise:
    runs-on: ubuntu-latest
    env:
      DB_SERVER: ${{ secrets.CLOUD_SQL_PRIVATE_IP }}
      DB_USER: ${{ secrets.CLOUD_SQL_USER }}
      DB_PASSWORD: ${{ secrets.CLOUD_SQL_PASS }}
      DB_DSN: pgsql:host=${{ secrets.CLOUD_SQL_PRIVATE_IP }};dbname=skyviewer
    steps:
      - uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: skyviewer
          credentials: ${{ secrets.GAE_SA }}
