name: 'Preview Dev PR'

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'closed'
    branches:
      - 'develop'

jobs:
  build-push-deploy:
    name: 'Deploy Preview Version'
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed'}}

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # gcloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.DEV_SA_KEY }}
        project_id: skyviewer
        export_default_credentials: true
    
    - name: Get app.yaml
      run: gcloud secrets versions access latest --secret=skyviewer-api-appyaml > app.yaml

    - name: Deploy to App Engine
      env:
        BRANCH_NAME: ${{ github.head_ref }}
      run: |
        gcloud app deploy app.yaml \
        --no-promote \
        --version=${BRANCH_NAME,,}

  cleanup:
    name: 'Cleanup PR Preview'
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed'}}

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # gcloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.DEV_SA_KEY }}
        project_id: skyviewer
        export_default_credentials: true        

    # Destruct!
    - name: Destroy version
      env:
        BRANCH_NAME: ${{ github.head_ref }}
      run: gcloud app versions delete ${BRANCH_NAME,,} --service=skyviewer-api       