name: 'Deploy to Dev'

on:
  push:
    branches:
      - 'develop'

jobs:
  build-push-deploy:
    name: 'Build and Deploy to Development'
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed'}}

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # gcloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.DEV_SA_KEY }}
        project_id: skyviewer
        export_default_credentials: true
    
    - name: Get app.yaml
      run: gcloud secrets versions access latest --secret=skyviewer-api-appyaml > app.yaml

    - name: Format version name
      id: version_name
      run: echo "version_name=$(echo \"${{ github.head_ref }}\" | sed 's/[_.,\/]/-/g' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Deploy to App Engine
      env:
        BRANCH_NAME: ${{ env.version_name }}
      run: |
        gcloud app deploy app.yaml \
          --promote
