# Builds, pushes, and deploys the Skyviewer API container
name: 'Build and deploy Skyviewer API to Google Cloud Run in Dev'

on:
  push:
    branches:
      - 'master'
  
jobs:
  build-push-deploy:
    name: 'Build, Publish, and Deploy'
    runs-on: ubuntu-latest

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # gcloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SKYVIEWER_INT_SERVICE_ACCOUNT }}
        project_id: edc-int-6c5e
        export_default_credentials: true

     # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
    - run: gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build Docker image
      run: |-
        docker build . \
          --tag "gcr.io/edc-int-6c5e/skyviewer-api:${{ github.sha }}"

    # Push the Docker image to Google Container Registry
    - name: Publish image to GCR
      run: |-
        docker push "gcr.io/edc-int-6c5e/skyviewer-api:${{ github.sha }}"

    - name: Get VPC connector name
      run: echo "vpc_connector=$(gcloud compute networks vpc-access connectors list --region=us-central1 --limit=1 --format='value(name)')" >> $GITHUB_ENV

    # Deploy to Cloud Run.
    - name: Deploy to Cloud Run
      id: deploy
      run: |-
        gcloud run deploy skyviewer-api-int \
        --image=gcr.io/edc-int-6c5e/skyviewer-api:${{ github.sha }} \
        --vpc-connector=${{ env.vpc_connector }} \
        --service-account=project-service-account@edc-int-6c5e.iam.gserviceaccount.com \
        --region=us-central1

    - name: Redirect traffic to new revision
      run: gcloud run services update-traffic skyviewer-api-int --region=us-central1 --to-latest