# Builds, pushes, and deploys the Skyviewer API container
name: 'Deploy to Integration'

on:
  push:
    branches:
      - 'master'
  
jobs:
  build-push-deploy:
    name: 'Build, Publish, and Deploy'
    runs-on: ubuntu-latest

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # gcloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SKYVIEWER_INT_SERVICE_ACCOUNT }}
        project_id: epo-integration-0e42
        export_default_credentials: true

     # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
    - run: gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build Docker image
      run: |-
        docker build . \
          --tag "gcr.io/epo-integration-0e42/skyviewer-api:${{ github.sha }}"

    # Push the Docker image to Google Container Registry
    - name: Publish image to GCR
      run: |-
        docker push "gcr.io/epo-integration-0e42/skyviewer-api:${{ github.sha }}"

    # Deploy to Cloud Run.
    - name: Deploy to Cloud Run
      id: deploy
      run: |
        gcloud run deploy skyviewer-api \
        --service-account=project-service-account@epo-integration-0e42.iam.gserviceaccount.com \
        --image=gcr.io/epo-integration-0e42/skyviewer-api:${{ github.sha }} \
        --region=us-central1


    # Ensure that traffic is directed to the latest revision. This is necessary because
    # the deploy-cloudrun action above is not capable of both deploying and redirecting
    # traffic in the same operation
    - name: Redirect traffic to the latest revision
      run: |
        gcloud run services update-traffic skyviewer-api \
        --platform managed \
        --region us-central1 \
        --to-revisions LATEST=100