  # Builds, pushes, and deploys the Skyviewer API container
name: 'Deploy PR Preview to Integration'

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'closed'
    branches:
      - 'master'

jobs:
  build-push-deploy:
    name: 'Build, Publish, and Deploy'
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed'}}

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print GitHub event action
      run: |
        echo "${{ github.event.action }}"

    # gcloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SKYVIEWER_INT_SERVICE_ACCOUNT }}
        project_id: epo-integration-0e42
        export_default_credentials: true

     # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build Docker image
      run: |-
        docker build \
          --tag "gcr.io/epo-integration-0e42/skyviewer-api:${{ github.sha }}" .

    # Push the Docker image to Google Container Registry
    - name: Publish image to GCR
      run: |-
        docker push "gcr.io/epo-integration-0e42/skyviewer-api:${{ github.sha }}"

    # Deploy to Cloud Run.
    - name: Deploy a tagged version to Cloud Run without redirecting traffic
      id: deploy
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service: skyviewer-api
        image: gcr.io/epo-integration-0e42/skyviewer-api:${{ github.sha }}    
        credentials: ${{ secrets.GCP_SA_KEY }}
        no_traffic: true
        tag: ${{ github.head_ref }}
        region: us-central1

    - name: Post the URL to the PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          A preview of this PR will be available at {{ steps.deploy.outputs.url }} until the request is closed.
        reactions: '+1'

  remove-tag:
    name: 'Remove branch tag'
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed'}}

    steps:
      # gcloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SKYVIEWER_INT_SERVICE_ACCOUNT }}
        project_id: epo-integration-0e42
        export_default_credentials: true

      # Remove the branch tag when the PR is closed
    - name: Remove branch tag
      run: |-
        gcloud run services update-traffic skyviewer-api \
        --platform managed \
        --service-account project-service-account@epo-integration-0e42.iam.gserviceaccount.com
        --region us-central1